apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: credit-agent-serving
  annotations:
    scenarios.ai.sap.com/description: "AI Agent for Credit Note Processing"
    scenarios.ai.sap.com/name: "credit-agent"
    executables.ai.sap.com/description: "Serving executable for credit workflow agent"
    executables.ai.sap.com/name: "credit-agent-server"
  labels:
    scenarios.ai.sap.com/id: "credit-agent"
    executables.ai.sap.com/id: "credit-agent-server"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1"
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 3
        containers:
          - name: kserve-container
            image: "ghcr.io/pranavp673/credit-agent:latest"
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: AICORE_BASE_URL
                value: "https://api.ai.prod.us-east-1.aws.ml.hana.ondemand.com"
              - name: AICORE_AUTH_URL
                value: "https://dev-us-at5dbujw.authentication.us10.hana.ondemand.com"
              - name: AICORE_CLIENT_ID
                value: "sb-76eb51b7-4c36-4686-b652-edb70cce0c0c!b123476|aicore!b164"
              - name: AICORE_CLIENT_SECRET
                value: "457f3080-87ac-4e94-b5cb-888e3e6d679d$jplaiifcOIPwIaZEppNnjNhs1eaKX-MBpW7caq17DBE="
              - name: AICORE_RESOURCE_GROUP
                value: "default"
              - name: GENAI_HUB_DEPLOYMENT_ID
                value: "dfbb456bbb32fd15"
              - name: AGENT_MODEL
                value: "gpt-4o"
